### ISSUE TITLE
New rust version build failed

### ISSUE THREAD

**Issue by xidoo123** [fuzzware-fuzzer/hoedur#1]
Hi, I got this error when I tried to build debug version. 

```
$ cargo run --bin hoedur-arm -- $ARGS
...
error[E0512]: cannot transmute between types of different sizes, or dependently-sized types
  --> /home/xdchase/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rune-0.12.3/src/hash.rs:68:18
   |
68 |         unsafe { mem::transmute(type_id) }
   |                  ^^^^^^^^^^^^^^
   |
   = note: source type: `std::any::TypeId` (128 bits)
   = note: target type: `hash::Hash` (64 bits)

error[E0512]: cannot transmute between types of different sizes, or dependently-sized types
  --> /home/xdchase/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rune-0.12.3/src/modules/any.rs:15:14
   |
15 |     unsafe { std::mem::transmute(item.type_hash().expect("no type known for i...
   |              ^^^^^^^^^^^^^^^^^^^
   |
   = note: source type: `hash::Hash` (64 bits)
   = note: target type: `modules::any::TypeId` (128 bits)

For more information about this error, try `rustc --explain E0512`.
error: could not compile `rune` (lib) due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
```
This is my rust version

```
$ cargo -V
cargo 1.73.0 (9c4383fb5 2023-08-26)
$ rustc -V
rustc 1.73.0 (cc66ad468 2023-10-03)
```

But after I revert rust version back to `rustc 1.66.1 (90743e729 2023-01-10)` everything works pretty well. Not sure why it's not compatible with the newer version rust.

**Comment by SWW13** [comment]
I updated the dependencies, the build should now work with `rustc 1.73.0`.
